version: '3'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  serverless-redis-http:
    ports:
      - '8079:80'
    image: ghcr.io/ikatsuba/serverless-redis:latest
    environment:
      PORT: 80
      SR_TOKEN: example_token
      REDIS_URL: 'redis://redis:6379'
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
