name = "revelio"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[observability]
enabled = true
head_sampling_rate = 1

[[analytics_engine_datasets]]
binding = "analytics"
dataset = "revelio-counts"

[[d1_databases]]
binding = "revelioDB"
database_name = "revelio-db"
database_id = "28350fc4-5854-4748-b42c-ffa92d28ddec"

[vars]
BOT_WEBHOOK_URL="https://revelio.katsuba.workers.dev/api/tg/webhook"
CLOUDFLARE_ACCOUNT_ID="53683e9c95b74c0aae7b4b9821b8c53f"
IMAGE_MODEL="dall-e-3"
OPENAI_API_URL="https://gateway.ai.cloudflare.com/v1/53683e9c95b74c0aae7b4b9821b8c53f/revelio-prod/openai"
PERPLEXITY_API_URL="https://gateway.ai.cloudflare.com/v1/53683e9c95b74c0aae7b4b9821b8c53f/revelio-prod/perplexity-ai"
QSTASH_URL="https://qstash.upstash.io"
REMINDERS_AFTER_NOTIFY_CALLBACK_URL="https://revelio.katsuba.workers.dev/api/reminders/after-notify"
TELEGRAM_API_ID="73603"
UPSTASH_REDIS_URL="https://settled-skylark-22019.upstash.io"
UPSTASH_VECTOR_REST_URL="https://known-lamb-99258-eu1-vector.upstash.io"
NODE_ENV="production"
